version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    networks:
      - webnet
  
  backend:
    container_name: movie-library-backend
    build:
      context: .
      target: final
    env_file:
      - .env
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    depends_on:
      - mongodb
    networks:
      - webnet

volumes:
  mongodb:

networks:
  webnet: